/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ys.parts.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Parts service. Represents a row in the &quot;Inventory_Parts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ys.parts.model.impl.PartsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ys.parts.model.impl.PartsImpl}.
 * </p>
 *
 * @author shashantp
 * @see Parts
 * @see com.ys.parts.model.impl.PartsImpl
 * @see com.ys.parts.model.impl.PartsModelImpl
 * @generated
 */
public interface PartsModel extends BaseModel<Parts> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parts model instance should use the {@link Parts} interface instead.
	 */

	/**
	 * Returns the primary key of this parts.
	 *
	 * @return the primary key of this parts
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this parts.
	 *
	 * @param primaryKey the primary key of this parts
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the part ID of this parts.
	 *
	 * @return the part ID of this parts
	 */
	public long getPartId();

	/**
	 * Sets the part ID of this parts.
	 *
	 * @param partId the part ID of this parts
	 */
	public void setPartId(long partId);

	/**
	 * Returns the company ID of this parts.
	 *
	 * @return the company ID of this parts
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this parts.
	 *
	 * @param companyId the company ID of this parts
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this parts.
	 *
	 * @return the group ID of this parts
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this parts.
	 *
	 * @param groupId the group ID of this parts
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the manuf ID of this parts.
	 *
	 * @return the manuf ID of this parts
	 */
	public long getManufId();

	/**
	 * Sets the manuf ID of this parts.
	 *
	 * @param manufId the manuf ID of this parts
	 */
	public void setManufId(long manufId);

	/**
	 * Returns the name of this parts.
	 *
	 * @return the name of this parts
	 */
	public String getName();

	/**
	 * Returns the localized name of this parts in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this parts
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this parts in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this parts. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this parts in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this parts
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this parts in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this parts
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this parts.
	 *
	 * @return the locales and localized names of this parts
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this parts.
	 *
	 * @param name the name of this parts
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this parts in the language.
	 *
	 * @param name the localized name of this parts
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this parts in the language, and sets the default locale.
	 *
	 * @param name the localized name of this parts
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this parts from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this parts
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this parts from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this parts
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the part number of this parts.
	 *
	 * @return the part number of this parts
	 */
	@AutoEscape
	public String getPartNumber();

	/**
	 * Sets the part number of this parts.
	 *
	 * @param partNumber the part number of this parts
	 */
	public void setPartNumber(String partNumber);

	/**
	 * Returns the reorder date of this parts.
	 *
	 * @return the reorder date of this parts
	 */
	public Date getReorderDate();

	/**
	 * Sets the reorder date of this parts.
	 *
	 * @param reorderDate the reorder date of this parts
	 */
	public void setReorderDate(Date reorderDate);

	/**
	 * Returns the quantity of this parts.
	 *
	 * @return the quantity of this parts
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this parts.
	 *
	 * @param quantity the quantity of this parts
	 */
	public void setQuantity(int quantity);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	public Object clone();

	public int compareTo(Parts parts);

	public int hashCode();

	public CacheModel<Parts> toCacheModel();

	public Parts toEscapedModel();

	public Parts toUnescapedModel();

	public String toString();

	public String toXmlString();
}